site_name: "Projet de S2 : Guide de survie"
site_description: "Un guide pour bien gérer son projet de S2 à EPITA"
site_url: https://s2guide.epita.it/

repo_name: SheatNoisette/SupProjectStarterGuide
repo_url: https://github.com/SheatNoisette/SupProjectStarterGuide
copyright: 'CC BY NC 4.0 - Benoît M. et Luca C. - 2021'

theme:
    name: 'material'
    custom_dir: 'custom_theme' # for Matomo Analytics support
    language: fr

nav:
- Introduction: 'index.md'
- Guide: 'guide.md'
- Liens utiles: 'useful-links.md'
- Licence: 'license.md'
