
name: Deploy to mkdocs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install pip
        run: |
          sudo apt update
          sudo apt install python3-pip make -y

      # Runs a set of commands using the runners shell
      - name: Install Deps
        run: |
          pip3 install -r requirements.txt
      - name: Deploy
        run: make deploy
